name: onnx_merge
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - cudatoolkit=11.0
  - pandas<0.26
  - matplotlib
  - jupyter
  - nbconvert
  - uproot
  - scipy
  - tqdm
  - scikit-learn
  - pip==21.1.3
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html 
    - torch==1.9.0+cpu
    - torchvision==0.10.0+cpu
    - torchaudio===0.9.0
    - numpy
    - protobuf
    - onnx
    - tensorflow==2.3.1
    - h5pickle==0.4.2
    - autopep8==1.5.5
    - onnxoptimizer
    - keras2onnx==1.7.0
    - pytest
    - tf2onnx==1.9.1

